# Generated by Django 3.1.7 on 2021-03-11 16:57

from django.db import migrations, models

def apply_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.bulk_create([
        Group(name=u'user_permission')
    ])


def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(
        name__in=[
            u'user_permission'
        ]
    ).delete()


class Migration(migrations.Migration):
    initial = False

    dependencies = [
       ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]
